---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  interval: 1h0m0s
  values:
    k8sServiceHost: 10.8.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDR: "172.16.0.0/12"
        clusterPoolIPv4PodCIDRList: ["172.16.0.0/12"]
        clusterPoolIPv4MaskSize: 24
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true   