---
apiVersion: storage.k8s.io/v1
kind: Storageclass
metadata:
  name: nfs-subdir-external-provisioner
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cluster.local/nfs-subdir-external-provisioner
  