apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: patches
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./patches
  prune: true
  wait: true